Attribute VB_Name = "Module1"
Public chkItemPos, chkcntPos, chkprPos, chkErrPos, chklng, Inputs, BackUp, BackUp2, strTxt, strTmp, ClipTexts As String
Public ChkString, bHan, bEng, bEtc, bJap1, bJap2 As Boolean
Public a, Opacity As Integer

Public Function ReplCase(Reptxt) As String
    ReplCase = Replace(Reptxt, "0", "")
    ReplCase = Replace(Reptxt, "1", "")
    ReplCase = Replace(Reptxt, "2", "")
    ReplCase = Replace(Reptxt, "3", "")
    ReplCase = Replace(Reptxt, "4", "")
    ReplCase = Replace(Reptxt, "5", "")
    ReplCase = Replace(Reptxt, "6", "")
    ReplCase = Replace(Reptxt, "7", "")
    ReplCase = Replace(Reptxt, "8", "")
    ReplCase = Replace(Reptxt, "9", "")
    ReplCase = Replace(Reptxt, " ", "")
    ReplCase = Replace(Reptxt, "!", "")
    ReplCase = Replace(Reptxt, "@", "")
    ReplCase = Replace(Reptxt, "#", "")
    ReplCase = Replace(Reptxt, "$", "")
    ReplCase = Replace(Reptxt, "%", "")
    ReplCase = Replace(Reptxt, "^", "")
    ReplCase = Replace(Reptxt, "&", "")
    ReplCase = Replace(Reptxt, "*", "")
    ReplCase = Replace(Reptxt, "(", "")
    ReplCase = Replace(Reptxt, ")", "")
    ReplCase = Replace(Reptxt, "-", "")
    ReplCase = Replace(Reptxt, "_", "")
    ReplCase = Replace(Reptxt, "=", "")
    ReplCase = Replace(Reptxt, "+", "")
    ReplCase = Replace(Reptxt, ":", "")
    ReplCase = Replace(Reptxt, ";", "")
    ReplCase = Replace(Reptxt, """", "")
    ReplCase = Replace(Reptxt, "'", "")
    ReplCase = Replace(Reptxt, "/", "")
    ReplCase = Replace(Reptxt, "?", "")
    ReplCase = Replace(Reptxt, "<", "")
    ReplCase = Replace(Reptxt, ">", "")
    ReplCase = Replace(Reptxt, ",", "")
    ReplCase = Replace(Reptxt, ".", "")
    ReplCase = Replace(Reptxt, "[", "")
    ReplCase = Replace(Reptxt, "]", "")
    ReplCase = Replace(Reptxt, "{", "")
    ReplCase = Replace(Reptxt, "}", "")
    ReplCase = Replace(Reptxt, "\", "")
    ReplCase = Replace(Reptxt, "|", "")
    ReplCase = Replace(Reptxt, "：", "")
    ReplCase = Replace(Reptxt, "¿", "")
    ReplCase = Replace(Reptxt, "。", "")
    ReplCase = Replace(Reptxt, "、", "")
    ReplCase = Replace(Reptxt, "、", "")
    ReplCase = Replace(Reptxt, "？", "")
End Function
